[Feature] #3 TabView, 현재 홈화면은 첫번째 탭, 두번째 화면은 히스토리 탭
DeveloperAcademy-POSTECH/River_BU_01 pull request #4
Opened 2022-06-30 11:28 UTC by rriver2

TabView로 두 뷰를 분리하고, 히스토리 탭을 구현했습니다.

관련 Issue : #3
- [x] 탭뷰를 만들어서 기존의 화면은 첫번째 탭 (SearchWordsView)과 히스토리 탭 (HistoryListView)으로 분리
- [x] 두번째 화면은 히스토리 탭 (HistoryListView)에 검색한 단어들의 히스토리를 저장하는 기능 구현

-------
다음 할 일 
- [ ] HistoryListView에서 단어 자체를 수정할 수 있는 기능

2022-07-01 02:15 UTC, DevKang requested changes
ViewModel의 역할에 대한 구현 경계가 조금 희미한 것 같습니다. 
### MVVM 패턴에서
1.  ViewModel 이 어떤 역할을 하는지
2. 해당 패턴에서 View 는 어느정도의 역할만 수행해야 하는지
3. ViewModel과 View 는 어떤 관계로 매칭이 되는지

위의 사항들을 한번 리서치 해보시고 정리해보시면 좋을 것 같아요.

2022-07-01 02:15 UTC, DevKang commented on River_cultureCenter/River_cultureCenter/SearchWords/AlertCountView.swift
> +struct AlertCountView: View{
경고창에서는 단순하게 데이터를 보여주는 역할만 하고 데이터를 조작하는 일을 하지 않기 때문에 굳이 ViewModel을 가지고 있는 것 보다는 어떤 종류의 경고인지(1이하인지, 15이상인지) 정도만 알고있으면 될 것 같아요.  실제로 코드에서 사용되는 ViewModel의 정보 역시 그 정도로 보이고요

2022-07-01 02:15 UTC, DevKang commented on River_cultureCenter/River_cultureCenter/SearchWords/AlertCountView.swift
> +            if viewModel.countedWord == 1 {
#1 의 리뷰를 참조해주세요 :)

2022-07-01 02:15 UTC, DevKang commented on River_cultureCenter/River_cultureCenter/SearchWords/CountViewModel.swift
> +    func awaitloadData() async{
이 함수의 역할이 do - try - catch 문 없애는 역할이라면 차라리 loadData() 쪽을 수정하는게 좋지 않을까요??

2022-07-01 02:15 UTC, DevKang commented on River_cultureCenter/River_cultureCenter/SearchWords/CountViewModel.swift
> +    func isNumberBiggerThan1() -> Bool {
여기도 #1 에서 코멘트 드린것 참조하셔서 count 데이터에 대한 검증로직을 만들어주시면 어떨까 싶습니다

2022-07-01 02:15 UTC, DevKang commented on River_cultureCenter/River_cultureCenter/SearchWords/EnglishWordListView.swift
> +        historyViewModel.wordList.append(viewModel.words)
HistoryViewModel 안에 있는 데이터들에 대해서 View에서 직접 조작을 하는것이 조금 위험해 보입니다.
히스토리 목록이 추가될 때마다 어떤 로직(예를 들자면 분석 데이터를 보낸다던가)이 실행되어야 한다라고 하면 .append() 와 같이 ViewModel의 데이터를 직접 수정한 부분 전부를 찾아야 하기 때문입니다.
데이터를 조작하는 역할을 ViewModel에 맡겼다면, ViewModel 이외의 부분에서는 데이터가 조작되는 일이 없게 잘 분리를 해주시는 것이 좋아요

2022-07-01 02:15 UTC, DevKang commented on River_cultureCenter/River_cultureCenter/SearchWords/SearchWordsView.swift
> +    func awaitloadData() async{
loadData(), awaitLoadData() 이 두개 함수의 혼용이 보입니다. 하나로 정리되면 좋을 것 같아요.

2022-07-01 02:15 UTC, DevKang commented on River_cultureCenter/River_cultureCenter/HistoryWords/HistoryViewModel.swift
> +
다른 코멘트에도 적었지만, ViewModel 안에서 다뤄지는 데이터에 대한 조작은 ViewModel 안에서 책임을 지는 것이 좋습니다. 지금 같은 경우에는 `@Published var wordList: [[String]]` 역시 해당 배열이 변경되는 모든 행위들은 ViewModel안에서 함수로 작성해서 View에서는 해당 함수를 통해서만 데이터를 변경할 수 있어야 합니다.

2022-07-04 06:35 UTC, rriver2 commented on River_cultureCenter/River_cultureCenter/SearchWords/AlertCountView.swift
> +            if viewModel.countedWord == 1 {
넵 ! 감사합니당 ~

2022-07-04 06:37 UTC, rriver2 commented on River_cultureCenter/River_cultureCenter/SearchWords/CountViewModel.swift
> +    func isNumberBiggerThan1() -> Bool {
이전 리뷰에서 확인하고 고쳤습니다 ! 감사합니다 !

2022-07-04 06:40 UTC, rriver2 commented on River_cultureCenter/River_cultureCenter/SearchWords/EnglishWordListView.swift
> +        historyViewModel.wordList.append(viewModel.words)
확인했습니다.. 구현에 눈이 멀어 로직을 생각 안했었네요 데이터 조작은 ViewModel에서만 일어나도록 변경했습니다 감사합니다 !

2022-07-04 07:02 UTC, rriver2 commented on River_cultureCenter/River_cultureCenter/HistoryWords/HistoryViewModel.swift
> +
변경했습니다 ! historyViewModel와 HistoryWordsView 한번 확인 부탁드려요 감사합니다 !

2022-07-04 07:03 UTC, rriver2 commented on River_cultureCenter/River_cultureCenter/SearchWords/SearchWordsView.swift
> +    func awaitloadData() async{
두 함수명을 View에서는 loadData(), ViewModel에서는 loadWordsAPI()로 변경했습니다 !

2022-07-04 07:04 UTC, rriver2 commented on River_cultureCenter/River_cultureCenter/SearchWords/CountViewModel.swift
> +    func awaitloadData() async{
이 부분은.. 한번 이야기를 여쭙고 싶습니다.. 🥹

2022-07-04 07:12 UTC, rriver2 commented on River_cultureCenter/River_cultureCenter/SearchWords/AlertCountView.swift
> +struct AlertCountView: View{
언급해주신 내용을 보고 viewBuilder 전체를 프로퍼티로 넘기지 말고 필요한 isCountValid만 넘길까 하다가, 
한 뷰에서만 사용되는 걸 확인하고 @ViewBuilder로 구현했습니다..! ㅎㅎ...

2022-07-04 09:43 UTC, merged

2022-07-04 10:02 UTC, rriver2 commented
> 3\. ViewModel과 View 는 어떤 관계로 매칭이 되는지

1,2번은 고민을 해서 답을 내렸는데 3번은 질문 내용을 이해하지 못했습니다 ㅠㅠ 질문을 좀 더 자세히 해주실 수 있을까요 ? 🥹


1. ViewModel 이 어떤 역할을 하는지
모델과 뷰를 연결해주는 역할로 모델이 변경되었을 때 뷰에 publish 하는 역할을 합니다.
또, history탭에서 사용자가 수정완료 이벤트가 발생하였을 때의 모델 변경의 기능을 수행합니다.

2. 해당 패턴에서 View 는 어느정도의 역할만 수행해야 하는지
View는 ViewModel에게 어떤 값을 변경해야 하는지 알려줍니다. 따라서 model을 변경하는 기능은 viewModel에서 이뤄지기 때문에 View에서는 변경이 되면 안됩니다..